SlimeStoreWeb/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SlimeStoreWeb.Contracts;
using SlimeStoreWeb.Data;
using SlimeStoreWeb.Models;
using SlimeStoreWeb.Repositories;

namespace SlimeStoreWeb.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper mapper;
        private readonly UserManager<Customer> userManager;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly ICartRepository cartRepository;

        public CartsController(ApplicationDbContext context, IMapper mapper, UserManager<Customer> userManager, IHttpContextAccessor httpContextAccessor, ICartRepository cartRepository)
        {
            _context = context;
            this.mapper = mapper;
            this.userManager = userManager;
            this.httpContextAccessor = httpContextAccessor;
            this.cartRepository = cartRepository;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            if(!User.Identity.IsAuthenticated)
            {
                return View();
            }

            var cart = await cartRepository.GetCart();

            var model = mapper.Map<CartViewModel>(cart);
            return View(model);
        }

        //0 is decrement, 1 is increment for operator input parameter
        public async Task<IActionResult> AdjustQuantity(int? id, int? op)
        {
            var cart = await cartRepository.GetCart();
            var item = cart.CartItems.FirstOrDefault(item => item.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            if(op == 0)
            {
                item.Quantity -= 1;
            }
            else if(op == 1)
            {
                item.Quantity += 1;
            }

            if (item.Quantity <= 0)
            {
                _context.CartItems.Remove(item);
            }
            else
            {
                _context.Update(item);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> DeleteItem(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var cart = await cartRepository.GetCart();

            if (cart == null)
            {
                return NotFound(); // Handle cart not found
            }

            var cartItem = _context.CartItems.Find(id);

            if (cartItem == null)
            {
                return NotFound(); // Handle cart item not found
            }

            try
            {
                cart.CartItems.Remove(cartItem);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                // Handle concurrency conflict (if needed)
                return RedirectToAction("ConcurrencyError", new { itemId = id });
            }
            catch (Exception)
            {
                // Handle other exceptions (e.g., database errors)
                return RedirectToAction("Error");
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Id,DateCreated,DateUpdated")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Id,DateCreated,DateUpdated")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Carts'  is null.");
            }
            var cart = await _context.Carts.FindAsync(id);
            if (cart != null)
            {
                _context.Carts.Remove(cart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
          return (_context.Carts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SlimeStoreWeb/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SlimeStoreWeb.Contracts;
using SlimeStoreWeb.Data;
using SlimeStoreWeb.Models;

namespace SlimeStoreWeb.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper mapper;
        private readonly UserManager<Customer> userManager;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly ICartRepository cartRepository;

        public ItemsController(ApplicationDbContext context, IMapper mapper, UserManager<Customer> userManager, IHttpContextAccessor httpContextAccessor, ICartRepository cartRepository)
        {
            _context = context;
            this.mapper = mapper;
            this.userManager = userManager;
            this.httpContextAccessor = httpContextAccessor;
            this.cartRepository = cartRepository;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var Items = await _context.Items
                .Include(q => q.ItemCategory)
                .ToListAsync();

            var model = mapper.Map<List<ItemViewModel>>(Items);
            return View(model);
        }

        public async Task<IActionResult> ItemsView()
        {
            var Items = await _context.Items
                .Include(q => q.ItemCategory)
                .ToListAsync();

            var model = mapper.Map<List<ItemViewModel>>(Items);
            return View(model);
        }

        public async Task<IActionResult> AddToCart(int? id, int quantity)
        {
            if(id == null)
            {
                return NotFound();
            }

            if(!User.Identity.IsAuthenticated)
            {
                return RedirectToAction(nameof(Details), new { id = id });
            }

            var cart = await cartRepository.GetCart();
            var existingItem = cart.CartItems.FirstOrDefault(item => item.Item.Id == id);
            //var existingItem = await _context.CartItems.FirstOrDefaultAsync(item => item.Item.Id == id);
            var item = await _context.Items.FindAsync(id);

            if(item == null)
            {
                return NotFound();
            }

            var cartItem = new CartItem()
            {
                Quantity = quantity,
                Item = item
            };

            if (cart != null) //cart exists
            {
                if(existingItem != null) //item exists in cart
                {
                    existingItem.Quantity += quantity;

                    _context.Update(existingItem);
                }
                else //item doesn't exist in cart
                {
                    cart.CartItems.Add(cartItem);

                    _context.Update(cart);
                }
            }
            else //cart doesn't exist
            {
                var userId = (await userManager.GetUserAsync(httpContextAccessor?.HttpContext?.User)).Id;

                var newCart = new Cart()
                {
                    UserId = userId,
                    CartItems = new List<CartItem>()
                    {
                        cartItem
                    }
                };

                await cartRepository.AddAsync(newCart);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = id });
        }

        public async Task<IActionResult> AddToCartQuick(int? id, string returnUrl)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var item = await _context.Items.FindAsync(id);

                if (item == null)
                {
                    return NotFound();
                }

                if (!User.Identity.IsAuthenticated)
                {
                    return Redirect(returnUrl);
                }

                var cart = await cartRepository.GetCart();

                var existingItem = cart.CartItems.FirstOrDefault(item => item.Item.Id == id);

                if (existingItem == null)
                {
                    var cartItem = new CartItem()
                    {
                        Item = item,
                        Quantity = 1
                    };

                    if (cart == null)
                    {
                        var userId = (await userManager.GetUserAsync(httpContextAccessor?.HttpContext?.User)).Id;

                        cart = new Cart()
                        {
                            UserId = userId,
                            CartItems = new List<CartItem>() { cartItem }
                        };

                        await cartRepository.AddAsync(cart);
                    }
                    else
                    {
                        cart.CartItems.Add(cartItem);
                        await _context.SaveChangesAsync();
                    }
                }
                else
                {
                    existingItem.Quantity += 1;
                    await _context.SaveChangesAsync();
                }

                return Redirect(returnUrl);
            }
            catch (Exception ex)
            {
                // Handle exceptions, log errors, and return an appropriate error response.
                return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred.");
            }
        }


        public async Task<IActionResult> ItemsFavoriteView()
        {
            if(User.Identity.IsAuthenticated)
            {
                var userId = (await userManager.GetUserAsync(httpContextAccessor?.HttpContext?.User)).Id;
                var user = await _context.Users
                    .Include(p => p.FavoriteItems)
                    .FirstOrDefaultAsync(q => q.Id == userId);

                if (user == null)
                {
                    return NotFound();
                }

                var model = mapper.Map<List<ItemViewModel>>(user.FavoriteItems);
                return View(model);
            }
            return View();
            
        }


        public async Task<IActionResult> FavoriteItem(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = _context.Items.FirstOrDefault(x => x.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            if(User.Identity.IsAuthenticated)
            {
                var userId = (await userManager.GetUserAsync(httpContextAccessor?.HttpContext?.User)).Id;
                var user = await _context.Users
                    .Include(p => p.FavoriteItems)
                    .FirstOrDefaultAsync(q => q.Id == userId);

                if (user == null)
                {
                    return NotFound();
                }

                if (user.FavoriteItems.Contains(item))
                {
                    user.FavoriteItems.Remove(item);
                }
                else
                {
                    user.FavoriteItems.Add(item);
                }

                _context.Update(user);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Details), new { id = id });
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            var relatedItems = await _context.Items
                                .Where(q => q.IsFeatured == true)
                                .ToListAsync();
            
            if(relatedItems == null)
            {
                ViewBag.RelatedItems = null;
            }
            else
            {
                var relatedItemsViewModel = mapper.Map<List<ItemViewModel>>(relatedItems);
                ViewBag.RelatedItems = relatedItemsViewModel;
            }

            var model = mapper.Map<ItemViewModel>(item);

            if (User.Identity.IsAuthenticated)
            {
                var userId = (await userManager.GetUserAsync(httpContextAccessor?.HttpContext?.User)).Id;
                var user = await _context.Users
                    .Include(p => p.FavoriteItems)
                    .FirstOrDefaultAsync(q => q.Id == userId);

                if (user == null)
                {
                    return NotFound();
                }

                if (user.FavoriteItems.Contains(item))
                {
                    model.IsFavorited = true;
                }
                else
                {
                    model.IsFavorited = false;
                }
            }
            return View(model);
            
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            var categories = _context.Categories.ToList();
            var model = new ItemCreateViewModel()
            {
                Categories = new SelectList(categories, "Id", "Name")
            };

            return View(model);
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

SlimeStoreWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using SlimeStoreWeb.Data;
@inject SignInManager<Customer> SignInManager
@inject UserManager<Customer> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerceStoreWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerceStoreWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" asp-append-version="true" />
</head>

<body class="bg-green">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-green-2 fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-white comic" asp-area="" asp-controller="Home" asp-action="Index">SLIME EMPORIUM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-white comic" asp-area="" asp-controller="Items" asp-action="ItemsView">SHOP ALL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-white comic" asp-area="" asp-controller="Items" asp-action="ItemsFavoriteView">FAVORITES</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fw-bold text-white comic" asp-area="" asp-controller="Carts" asp-action="Index">CART</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle fw-bold text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                ADMIN
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">ITEMS</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">CATEGORIES</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 mt-3 comic">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-center mt-5 bg-green3">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img src="/assets/slime-logo.jpg" alt="Logo" class="footer-logo rounded">
                </div>
                <div class="col-md-4">
                    <div class="footer-links">
                        <a href="#" class="fw-bold comic">FAQ</a>
                        <a href="#" class="fw-bold comic">CONTACT US</a>
                        <a href="#" class="fw-bold comic">PRIVACY POLICY</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="social-icons">
                        <a href="#" target="_blank"><i class="fab fa-facebook"></i></a>
                        <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>